version: '3.8'

services:
  astro-portfolio:
    build: .
    container_name: astro-portfolio
    restart: unless-stopped
    networks:
      - shared_portainer_network
    ports:
      - '3000:3000'
    # Add healthcheck
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shared_portainer_network:
    external: true
