version: '3.8'

services:
  astro-dev:
    image: node:18-alpine
    container_name: astro-dev
    restart: unless-stopped
    volumes:
      - .:/app # Mount the project directory for live updates
    working_dir: /app
    command: npm run dev -- --host
    ports:
      - '4321:4321' # Expose dev server port
